### PR TITLE
Added the documentation for amplitude

### PR DESCRIPTION
**Pull request by ojninja16**
Please DO NOT DELETE this template. Fill it. PR without your declaration that you license your code under MIT will 
be discarded. 

Tips
----------------

 * Give the same name to the pull request as the name of ticket if possible
 * Make the title in form of: Pull request title (#<issue-id>)
 * Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 * Test your code thoroughly before PR.

Pull Request title
Added the documentation for amplitude

     Pull request title (#<issue-id>)

Pull Request description
I added a small description along with steps required to obtain API credentials for Amplitude
-----
We need your declaration that your contribution is MIT licensed without it, we can not merge your code.
To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licensed under the [MIT license](https://opensource.org/licenses/MIT)

### CODE REVIEW

**Comment by ojninja16** [comment]
@atompie I have added the documentation for amplitude with my limited knowledge and some research ......feel free to point out my mistakes...thanks!

**Review by atompie — COMMENTED** [review]
It seems fine. I will review it today in the afternoon. Thanks.

**Comment by atompie** [comment]
Your PR is merged and already integrated in the system. Thanks. 
Screenshot from 2022-10-04 21-08-46

**Comment by ojninja16** [comment]
Thanks  for giving me this opportunity...

**Pull request merged**
