### PR TITLE
Document all documented action plugins (Issue #817 in tracardi repository)

### PR DESCRIPTION
**Pull request by Kaushik-Iyer**
Title:
Document all documented action plugins (Issue #817 in tracardi repository)

Description:
Listing down all the action plugins that currently require documentation.

 - [x] I hereby declare this contribution to be licensed under the [MIT license](https://opensource.org/licenses/MIT)

### CODE REVIEW

**Comment by Kaushik-Iyer** [comment]
@atompie how do I solve the license issue

**Comment by atompie** [comment]
@Kaushik-Iyer hi could you elaborate what you mean by license issues?

**Comment by Kaushik-Iyer** [comment]
Oh that MIT license check. Can you merge this PR now if it is correct? I wanna be one of the first 50000 in hacktoberfest :D

**Comment by atompie** [comment]
It is perfectly fine as long as you're agreed it to be MIT license. I will check your PR when I am at my desk.

**Pull request merged**
